spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party
server:
  port: 30000

alibaba:
  cloud:
    access-key: xxxx
    secret-key: xxxx
    oss:
      endpoint: xxxx
    sms:
      host: xxxx
      path: /sms/smsSend
      template: xxxx
      smssign: xxxx
      appcode: xxxx
